// Competition.java
// Safiqur Rahman, 22008929
import java.util.ArrayList;
import java.util.List;

public class Competition {
    private List<Match> matches;

    public Competition() {
        matches = new ArrayList<>();
    }

    public void add(Match match) {
        return 0;
    }

    public void remove(Match match) {
        return 0;
    }

    public void print() {
        return 0;
    }

    public Match find(int roundNumber) {
        return 0;
    }
}