// GameServer.java
// Danish Harith, 22009489
import java.util.ArrayList;
import java.util.List;

public class GameServer {
    private List<Competition> competitions;

    public GameServer() {
        competitions = new ArrayList<>();
    }

    public void add(Competition competition) {
        return 0;
    }

    public void remove(Competition competition) {
        return 0;
    }

    public void print() {
        return 0;
    }

    public Competition find(int index) {
        return 0;
    }
}