// Players.java
// Amin Zufar, 24000162
import java.util.ArrayList;
import java.util.List;

public class Players {
    private List<Player> playerList;

    public Players() {
        playerList = new ArrayList<>();
    }

    public void add(Player player) {
        return 0;
    }

    public void remove(Player player) {
        return 0;
    }

    public void print() {
        return 0;
    }

    public Player find(int id) {
        return 0;
    }
}